### ISSUE TITLE
Ошибка при запуске примера

### ISSUE THREAD

**Issue by ghost** [OwlSoul/YandexTransportWebdriverAPI-Python#3]
Здравствуйте, нашел ваш проект очень нужно достать данные по маршрутам, но при запуске тестового примера вылезает такая ошибка: 
Traceback (most recent call last):
  File "/Volumes/Macintosh HD/test_task/import json.py", line 10, in <module>
    result_json = proxy.get_stop_info(stop_url)
  File "/Users/emilkarpikov/Library/Python/2.7/lib/python/site-packages/yandex_transport_webdriver_api/yandex_transport_proxy.py", line 303, in get_stop_info
    result = self._execute_get_query('getStopInfo', url, query_id, blocking, timeout, callback)
  File "/Users/emilkarpikov/Library/Python/2.7/lib/python/site-packages/yandex_transport_webdriver_api/yandex_transport_proxy.py", line 222, in _execute_get_query
    result =  self._single_query_blocking(sock, command)
  File "/Users/emilkarpikov/Library/Python/2.7/lib/python/site-packages/yandex_transport_webdriver_api/yandex_transport_proxy.py", line 100, in _single_query_blocking
    sock.sendall(bytes(command, 'utf-8'))
TypeError: str() takes at most 1 argument (2 given)
[Finished in 0.1s with exit code 1]

я уж и не знаю куда копать, буду оень признателен если поможете

**Comment by OwlSoul** [comment]
И тут я такой решил поотвечать всем на мертвые темы.


Оно снова живое, правда по getStopInfo там проблема - он теперь дергается как-то асинхронно что ли, пока там лютый костыль просто после дерганья нужной ссылки Selenium-ом ждать 30 секунд, после такого отдает данные почти всегда.

Да, Питон нужен 3й =)
